---
title: "Big test"
author: "Lance Nemecek"
date: "2024-05-09"
output: html_document
runtime: shiny
---
  
```{r}
#| include: FALSE
library(tidyverse)
library(stringr)
library(rvest)
library(httr)
```

Beast Function Alert!!!

For 100 Meter Runs right now.

```{r, include = FALSE}
read_track_tibbles100 <- function(urls) {
    html_list <- list() 
    
    for (url in urls) {
        TrackTables <- read_html(url)
        One_hundred_meters <- html_table(TrackTables, header = TRUE, fill = TRUE)[[1]]
        colnames(One_hundred_meters) <- paste0("Column_", 1:ncol(One_hundred_meters)) 
        html_list[[url]] <- as_tibble(One_hundred_meters)
    }
    return(html_list)
}

# Running the Code
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List")

track_data_tibbles100 <- read_track_tibbles100(urls)

combined_table100 <- bind_rows(track_data_tibbles100)

print(combined_table100)

combined_table100$event <- "one_hundred"
```

```{r, include = FALSE}
combined_table100 <- combined_table100 |>
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7, wind = Column_8)
```

200 Meters

```{r, include = FALSE}
read_track_tibbles200 <- function(urls) {
    html_list <- list() 
    
    for (url in urls) {
        TrackTables <- read_html(url)
        Two_hundred_meters <- html_table(TrackTables, header = TRUE, fill = TRUE)[[3]]
        colnames(Two_hundred_meters) <- paste0("Column_", 1:ncol(Two_hundred_meters)) 
        html_list[[url]] <- as_tibble(Two_hundred_meters)
    }
    return(html_list)
}

# Running the Code
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List")

track_data_tibbles200 <- read_track_tibbles200(urls)


combined_table200 <- bind_rows(track_data_tibbles200)

print(combined_table200)

combined_table200$event <- "two_hundred"
```

```{r, include = FALSE}
combined_table200 <- combined_table200 |>
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7, wind = Column_8)

```

400 meters
```{r, include = FALSE}
read_track_tibbles400 <- function(urls) {
    html_list <- list() 
    
    for (url in urls) {
        TrackTables <- read_html(url)
        Four_hundred_meters <- html_table(TrackTables, header = TRUE, fill = TRUE)[[5]]
        colnames(Four_hundred_meters) <- paste0("Column_", 1:ncol(Four_hundred_meters)) 
        html_list[[url]] <- as_tibble(Four_hundred_meters)
    }
    return(html_list)
}

# Running the Code
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List")

track_data_tibbles400 <- read_track_tibbles400(urls)


combined_table400 <- bind_rows(track_data_tibbles400)

print(combined_table400)

combined_table400$wind <- "NA"
combined_table400$event <- "four_hundred"
```

```{r, include = FALSE}
combined_table400 <- combined_table400 |>
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7)

```

800 meters
```{r, include = FALSE}
read_track_tibbles800 <- function(urls) {
    html_list <- list() 
    
    for (url in urls) {
        TrackTables <- read_html(url)
        Eight_hundred_meters <- html_table(TrackTables, header = TRUE, fill = TRUE)[[7]]
        colnames(Eight_hundred_meters) <- paste0("Column_", 1:ncol(Eight_hundred_meters)) 
        html_list[[url]] <- as_tibble(Eight_hundred_meters)
    }
    return(html_list)
}

# Running the Code
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List")

track_data_tibbles800 <- read_track_tibbles800(urls)


combined_table800 <- bind_rows(track_data_tibbles800)

print(combined_table800)

combined_table800$wind <- "NA"
combined_table800$event <- "eight_hundred"
```

```{r, echo = FALSE}
combined_table800 <- combined_table800 |>
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7)

```

1500 meters


```{r, include = FALSE}
read_track_tibbles1500 <- function(urls) {
    html_list <- list() 
    
    for (url in urls) {
        TrackTables <- read_html(url)
        if (length(html_table(TrackTables)) >= 9) {
            Fifteen_hundred_meters <- html_table(TrackTables, header = TRUE, fill = TRUE)[[9]]
            if (ncol(Fifteen_hundred_meters) > 0) {
                colnames(Fifteen_hundred_meters) <- paste0("Column_", 1:ncol(Fifteen_hundred_meters))
                html_list[[url]] <- as_tibble(Fifteen_hundred_meters)
            } else {
                message("Table at index 9 has no columns at URL: ", url)
            }
        } else {
            message("Table index 9 does not exist at URL: ", url)
        }
    }
    return(html_list)
}

# Running the Code
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List")

track_data_tibbles1500 <- read_track_tibbles1500(urls)

combined_table1500 <- bind_rows(track_data_tibbles1500)

print(combined_table1500)

combined_table1500$wind <- "NA"
combined_table1500$event <- "fifteen_hundred"
```

```{r, include = FALSE}
combined_table1500 <- combined_table1500 |>
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7)

```

5000 meters
```{r, include = FALSE}
read_track_tibbles5000 <- function(urls) {
    html_list <- list() 
    
    for (url in urls) {
        TrackTables <- read_html(url)
       Fifty_hundred_meters <- html_table(TrackTables, header = TRUE, fill = TRUE)[[11]]
        colnames(Fifty_hundred_meters) <- paste0("Column_", 1:ncol(Fifty_hundred_meters)) 
        html_list[[url]] <- as_tibble(Fifty_hundred_meters)
    }
    return(html_list)
}

# Running the Code
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List")

track_data_tibbles5000 <- read_track_tibbles5000(urls)


combined_table5000 <- bind_rows(track_data_tibbles5000)

print(combined_table5000)

combined_table5000$wind <- "NA"
combined_table5000$event <- "five_k"
```

```{r, include = FALSE}
combined_table5000 <- combined_table5000 |>
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7)

```

10000 meters
```{r, include = FALSE}
read_track_tibbles10000 <- function(urls) {
    html_list <- list() 
    
    for (url in urls) {
        TrackTables <- read_html(url)
       Ten_thousand_meters <- html_table(TrackTables, header = TRUE, fill = TRUE)[[13]]
        colnames(Ten_thousand_meters) <- paste0("Column_", 1:ncol(Ten_thousand_meters)) 
        html_list[[url]] <- as_tibble(Ten_thousand_meters)
    }
    return(html_list)
}

# Running the Code
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List")

track_data_tibbles10000 <- read_track_tibbles10000(urls)


combined_table10000 <- bind_rows(track_data_tibbles10000)

print(combined_table10000)

combined_table10000$wind <- "NA"
combined_table10000$event <- "ten_k"
```

```{r, include = FALSE}
combined_table10000 <- combined_table10000 |>
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7)

```

```{r, include = FALSE}
all_running_events <- rbind(combined_table100, combined_table200, combined_table400, combined_table800, combined_table1500, combined_table5000, combined_table10000)

```

```{r}
all_running_events <- all_running_events %>%
    mutate(date = mdy(date)) %>%
    mutate(year_date = year(date))
```


110 Hurdles
```{r}
read_track_tibbles110H <- function(urls) {
    html_list <- list()
    
    for (url in urls) {
        TrackTables <- read_html(url)
        Hurdles_110 <- html_table(TrackTables, header = TRUE, fill = TRUE)[[16]]
        colnames(Hurdles_110) <- paste0("Column_", 1:ncol(Hurdles_110))
        
        # Convert all columns to character to prevent data type mismatch
        Hurdles_110[] <- lapply(Hurdles_110, as.character)
        
        html_list[[url]] <- as_tibble(Hurdles_110)
    }
    return(html_list)
}

# URLs to fetch data from
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List"
)

# Read and combine data
track_data_tibbles110H <- read_track_tibbles110H(urls)
combined_table110H <- bind_rows(track_data_tibbles110H)

# Optionally, rename columns if you know their meaning
combined_table110H <- combined_table110H |> 
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7, wind = Column_8)

print(combined_table110H)

combined_table110H$event <- "110hurdle"
```


400 Hurdles
```{r}
# Function to read data from URLs and process tables specific to 400 hurdles
read_track_tibbles400H <- function(urls) {
    html_list <- list()
    
    for (url in urls) {
        TrackTables <- read_html(url)
        # Assume the 400 Hurdles is at a different index, you need to check this
        Hurdles_400 <- html_table(TrackTables, header = TRUE, fill = TRUE)[[17]]  # Update index as needed
        colnames(Hurdles_400) <- paste0("Column_", 1:ncol(Hurdles_400))
        
        # Convert all columns to character to prevent data type mismatch
        Hurdles_400[] <- lapply(Hurdles_400, as.character)
        
        html_list[[url]] <- as_tibble(Hurdles_400)
    }
    return(html_list)
}

# List of URLs to fetch data from (update these URLs to the relevant pages for 400 hurdles)
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List"
)

# Read and combine data
track_data_tibbles400H <- read_track_tibbles400H(urls)
combined_table400H <- bind_rows(track_data_tibbles400H)

# Rename columns based on your understanding of the data
combined_table400H <- combined_table400H |> 
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7)

print(combined_table400H)

combined_table400H$wind <- "NA"
combined_table400H$event <- "400hurdle"


```

3000 SteepLechase
```{r}
# Function to read data from URLs and process tables specific to 3000 steeplechase
read_track_tibbles3000SC <- function(urls) {
    html_list <- list()
    
    for (url in urls) {
        TrackTables <- read_html(url)
        # You need to find the correct index for the 3000 Steeplechase table, this is just a placeholder
        Steeplechase_3000 <- html_table(TrackTables, header = TRUE, fill = TRUE)[[19]]  # Update index as needed
        colnames(Steeplechase_3000) <- paste0("Column_", 1:ncol(Steeplechase_3000))
        
        # Convert all columns to character to prevent data type mismatch
        Steeplechase_3000[] <- lapply(Steeplechase_3000, as.character)
        
        html_list[[url]] <- as_tibble(Steeplechase_3000)
    }
    return(html_list)
}

# List of URLs to fetch data from (update these URLs to the relevant pages for 3000 Steeplechase)
urls <- c(
    "https://www.tfrrs.org/lists/4723/MIAC_Outdoor_Performance_List",
    "https://tf.tfrrs.org/lists/4254/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3819/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/3354/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2590/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/2217/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1978/MIAC_Outdoor_Performance_List",
    "https://www.tfrrs.org/lists/1562/MIAC_Outdoor_Performance_List"
)

# Read and combine data
track_data_tibbles3000SC <- read_track_tibbles3000SC(urls)
combined_table3000SC <- bind_rows(track_data_tibbles3000SC)

# Rename columns based on your understanding of the data
combined_table3000SC <- combined_table3000SC |> 
  rename(seed = Column_1, name = Column_2, class_year = Column_3, school = Column_4, time = Column_5, meet = Column_6, date = Column_7)

print(combined_table3000SC)

combined_table110H$wind <- "NA"
combined_table110H$event <- "Steple"
```


```{r, echo = FALSE}
inputPanel(
  selectInput(inputId = "categ",
              label = h3("Event"),
              choices = c("one_hundred", "two_hundred", "four_hundred", "eight_hundred", "fifteen_hundred", "five_k", "ten_k"),
              selected = "one_hundred"),
  
  selectInput(inputId = "categ1",
              label = h3("Year"),
              choices = c("2024", "2023", "2022", "2021", "2019", "2018", "2017", "2015"),
              selected = "2024")
)
```

```{r, echo = FALSE}
testall_running_events <- all_running_events |>
  pivot_wider(names_from = event,
              values_from = school)
view(testall_running_events)
```


Column 
-------------------------


```{r}
renderPlot({
  testall_running_events |>
    filter(!is.na(.data[[input$categ]]), year(date) == as.numeric(input$categ1)) |>
    ggplot(aes(x = .data[[input$categ]])) +
    geom_bar()
})
```


